# -------------------------------- configuration for NTuples --------------------------------------#
ntuple_tree_name: '/dtNtupleProducer/DTTREE'

ntuple_selectors:
  baseline:
    src: "utils.filters.base_filters.baseline"

ntuple_preprocessors:
  # define the event preprocessors to be used in the ntuple
  genmuon_matcher:
    src: "utils.genmuon_functions.analyze_genmuon_matches"
  # genmuon_showerer:
  #   src: "utils.genmuon_functions.analyze_genmuon_showers"
  #   kwargs:
  #     method: 2
  real_shower_builder:
    src: "utils.shower_functions.build_real_showers"
    kwargs:
      threshold: 8
      debug: False
  fw_shower_analyzer:
    src: "utils.shower_functions.analyze_fwshowers"

# ------------------------------- configuration for particles -------------------------------------#

particle_types:
  digis:
    amount: 'digi_nDigis'
    attributes:
      wh: 
        branch: 'digi_wheel'
      sc: 
        branch: 'digi_sector'
      st: 
        branch: 'digi_station'
      sl: 
        branch: 'digi_superLayer'
      w: 
        branch: 'digi_wire'
      l: 
        branch: 'digi_layer'
      time: 
        branch: 'digi_time'
      BX:
        expr: 'time // 25 if time is not None else None'
    sorter:
      by: 'p.BX'
  segments:
    amount: 'seg_nSegments'
    attributes:
      wh: 
        branch: 'seg_wheel'
      sc: 
        branch: 'seg_sector'
      st: 
        branch: 'seg_station'
      phi: 
        branch: 'seg_posGlb_phi'
      eta: 
        branch: 'seg_posGlb_eta'
      nHits_phi: 
        branch: 'seg_phi_nHits'
      nHits_z: 
        branch: 'seg_z_nHits'
      t0_phi: 
        branch: 'seg_phi_t0'
      pos_locx_sl1: 
        branch: 'seg_posLoc_x_SL1'
      pos_locx_sl3: 
        branch: 'seg_posLoc_x_SL3'
      matched_genmuons: []
      matched_tps: []
  tps:  
    amount: 'ph2TpgPhiEmuAm_nTrigs'
    attributes:
      wh: 
        branch: 'ph2TpgPhiEmuAm_wheel'
      sc: 
        branch: 'ph2TpgPhiEmuAm_sector'
      st: 
        branch: 'ph2TpgPhiEmuAm_station'
      phi: 
        branch: 'ph2TpgPhiEmuAm_phi'
      phiB: 
        branch: 'ph2TpgPhiEmuAm_phiB'
      quality: 
        branch: 'ph2TpgPhiEmuAm_quality'
      rpcFlag: 
        branch: 'ph2TpgPhiEmuAm_rpcFlag'
      _BX: # first get the BX from the branch
        branch: 'ph2TpgPhiEmuAm_BX'
      BX: # then re-define the BX attribute to center it at 0
        expr: '_BX - 20'
      phires_conv:
        expr: '65536.0 / 0.5'
      matched_segments: []
      matched_genmuons: []
    filter: 'p.quality >= 0'
  genmuons:
    amount: 'gen_nGenParts'
    attributes:
      pt: 
        branch: 'gen_pt'
      eta: 
        branch: 'gen_eta'
      phi: 
        branch: 'gen_phi'
      charge: 
        branch: 'gen_charge'
      matched_segments: []
      matched_tps: []
      showered: False
    filter: 'abs(ev.gen_pdgId[p.index]) == 13'
    sorter:
      by: 'p.pt'
      reverse: True
  fwshowers:
    amount: 'ph2Shower_station'
    attributes:
      wh: 
        branch: 'ph2Shower_wheel'
      sc: 
        branch: 'ph2Shower_sector'
      st: 
        branch: 'ph2Shower_station'
      sl: 
        branch: 'ph2Shower_superlayer'
      nDigis: 
        branch: 'ph2Shower_ndigis'
      BX: 
        branch: 'ph2Shower_BX'
      min_wire: 
        branch: 'ph2Shower_min_wire'
      max_wire: 
        branch: 'ph2Shower_max_wire'
      avg_pos: 
        branch: 'ph2Shower_avg_pos'
      avg_time: 
        branch: 'ph2Shower_avg_time'
      wires_profile: 
        branch: 'ph2Shower_wires_profile'
  simhits:
    amount: 'simHit_nSimHits'
    attributes:
      wh: 
        branch: 'simHit_wheel'
      sc: 
        branch: 'simHit_sector'
      st: 
        branch: 'simHit_station'
      sl: 
        branch: 'simHit_superLayer'
      l: 
        branch: 'simHit_layer'
      w: 
        branch: 'simHit_wire'
      process_type: 
        branch: 'simHit_processType'
      particle_type: 
        branch: 'simHit_particleType'

# -------------------------------- configuration for histograms -----------------------------------#
histo_sources:
  - shower_histos

histo_names:
  # Histogram to fill - Uncomment or add histograms as needed. 
  # They should exist in any of the source modules
  # # --------- truth types --------- #
  # - showered_genmuon_meth1_eff
  # - showered_genmuon_meth2_eff
  # - showered_genmuon_meth3_eff
  # # ============ efficiencies ============ #
  # - fwshower_eff_MB1
  # - fwshower_eff_MB2
  # - fwshower_eff_MB3
  # - fwshower_eff_MB4
  - fwshower_eff_MB1_onlytpfp
  - fwshower_eff_MB2_onlytpfp
  - fwshower_eff_MB3_onlytpfp
  - fwshower_eff_MB4_onlytpfp
  # # ------ conf maps------
  # - shower_tpfptnfn_MB1
  # - shower_tpfptnfn_MB2
  # - shower_tpfptnfn_MB3
  # - shower_tpfptnfn_MB4
  # - shower_tpfptnfn_g4
  # # real showers
  # - realshower_type_dist_MB1
  # - realshower_type_dist_MB2
  # - realshower_type_dist_MB3
  # - realshower_type_dist_MB4
