!include ../yamls/run_config_v0.yaml

ntuple_preprocessors:
  real_shower_builder:
    src: "utils.shower_functions.build_real_showers"
    kwargs:
      threshold: 6
      debug: False

# -------------------------------- configuration for histograms -----------------------------------#
histo_sources:
  # define the source modules of the histograms
  - dtpr.utils.histograms.am_histos
  - shower_rates_histos

histo_names:
  # Histogram to fill - Uncomment or add histograms as needed. 
  # They should exist in any of the source modules
  - AM_rate_goodBX_MB1
  - AM_rate_goodBX_MB2
  - AM_rate_goodBX_MB3
  - AM_rate_goodBX_MB4
  - AM_rate_allBX_MB1
  - AM_rate_allBX_MB2
  - AM_rate_allBX_MB3
  - AM_rate_allBX_MB4
  - fwshower_rate_goodBX_MB1
  - fwshower_rate_goodBX_MB2
  - fwshower_rate_goodBX_MB3
  - fwshower_rate_goodBX_MB4
  - fwshower_rate_allBX_MB1
  - fwshower_rate_allBX_MB2
  - fwshower_rate_allBX_MB3
  - fwshower_rate_allBX_MB4

