!include ../yamls/run_config_v1.yaml
# -------------------------------- configuration for histograms -----------------------------------#
histo_sources:
  - barrel_filter_histograms

histo_names:
  - shower_showeredgenmuon_tag_eff_pttrend
  - shower_genmuon_tag_eff_pttrend_all
  - AMTp_showeredgenmuon_tag_eff_pttrend
  - AMTp_genmuon_tag_eff_pttrend_all
  - fwshower_eff_afterfilter_MB1
  - fwshower_eff_afterfilter_MB2
  - fwshower_eff_afterfilter_MB3
  - fwshower_eff_afterfilter_MB4
  - AMTpshowered_AMTps_eff_MB1
  - AMTpshowered_AMTps_eff_MB2
  - AMTpshowered_AMTps_eff_MB3
  - AMTpshowered_AMTps_eff_MB4
  - AMTpshoweredtagged_AMTps_eff_MB1
  - AMTpshoweredtagged_AMTps_eff_MB2
  - AMTpshoweredtagged_AMTps_eff_MB3
  - AMTpshoweredtagged_AMTps_eff_MB4
  - seg_eff_afterfilter_MB1
  - seg_eff_afterfilter_MB2
  - seg_eff_afterfilter_MB3
  - seg_eff_afterfilter_MB4
  - showers_classification
  - showers_classification_MB1  
  - showers_classification_MB2
  - showers_classification_MB3
  - showers_classification_MB4
